openapi: 3.0.0
info:
  title: Gestión de Usuarios
  description: API para el servicio de gestión de usuarios.
  version: 1.0.0
servers:
  - url: https://localhost:8080/users
    description: Servidor de desarrollo
tags:
  - name: users
    description: Operations about users

paths:
  /users:
    post:
      tags:
        - users
      summary: Creación de un usuario
      description: Creación de un usuario en la base de datos
      operationId: save
      requestBody:
        required: true
        description: Usuario a crear
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Usuario creado
    get:
      tags:
        - users
      summary: Obtener todos los usuarios
      operationId: findAllUsers
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'


  /users/{id}:
    get:
      tags:
        - users
      summary: Obtener los detalles de un usuario
      operationId: findById
      parameters:
        - in: path
          name: id
          description: 'The id that needs to be fetched.'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: operation OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid id supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    delete:
      tags:
        - users
      summary: Eliminar un usuario
      operationId: deleteUserById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Usuario eliminado
    put:
      tags:
        - users
      summary: Actualizar un usuario existente
      description: Actualiza la información de un usuario identificado por su ID
      operationId: updateUser
      parameters:
        - in: path
          name: id
          description: 'ID del usuario a actualizar'
          required: true
          schema:
            type: string
      requestBody:
        required: true
        description: Datos actualizados del usuario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Usuario actualizado correctamente
        '400':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

  /users/dni/{dni}:
    get:
      tags:
        - users
      summary: Obtener un usuario por DNI
      operationId: getUserByDni
      parameters:
        - in: path
          name: dni
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalles del usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users/email/{email}:
    get:
      tags:
        - users
      summary: Obtener un usuario por email
      operationId: getUserByEmail
      parameters:
        - in: path
          name: email
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalles del usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        surname:
          type: string
        phone:
          type: string
        email:
          type: string
        dni:
          type: string
        password:
          type: string
        city:
          type: string
        country:
          type: string
        address:
          type: string
        dateOfBirth:
          type: string
          format: date
        dateOfRegistration:
          type: string
          format: date
        dateOfLastUpdate:
          type: string
          format: date

    ErrorMessage:
      type: object
      properties:
        statusCode:
          type: integer
        timestamp:
          type: string
          format: date-time
        message:
          type: string
        description:
          type: string